title: Joshua Wenning
description: Designer and developer creating thoughtful experiences across digital and print.
url: https://joshuawenning.com

social:
  linkedin: https://www.linkedin.com/in/joshuawenning/
  x: https://x.com/joshuawenning

#https://github.com/jekyll/jekyll/issues/7478#issuecomment-454419470
theme: null

sass:
  style: compressed
